name: DynEconomy
main: hu.durato.dyneconomy.DynEconomy
version: 1.0
commands:
   updatesigns:
      description: Update signs throughout the server.
      usage: /updatesigns
      permission: dyneconomy.updatesigns
      permission-message: You don't have permission!
   decayprices:
      description: Decay prices throughout the server.
      usage: /decayprices
      permission: dyneconomy.decayprices
      permission-message: You don't have permission!
depend: [Essentials]
permissions:
   dyneconomy.*:
      description: Gives access to all dyneco permissions
      children:
         dyneconomy.sign.create: true
         dyneconomy.sign.use: true
         dyneconomy.sign.buy: true
         dyneconomy.sign.sell: true
   dyneconomy.sign.create:
      description: Allows you to create a dyneco sign
      default: op
   dyneconomy.sign.use:
      description: Allows you to use a dyneco sign
      default: true
      children:
         dyneconomy.sign.buy: true
         dyneconomy.sign.sell: true
   dyneconomy.sign.buy:
      description: Allows you to buy with a dyneco sign
      default: true
   dyneconomy.sign.sell:
      description: Allows you to sell with a dyneco sign
      default: true